directories:
  output: ../release
  buildResources: build
appId: com.shosha.mart
productName: ShoshaMart POS
publish:
  provider: github
  owner: FuncSmile
  repo: shosha_market
  releaseType: draft
files:
  - filter:
      - main.js
      - updater.js
      - package.json
  - from: ../renderer/dist
    to: renderer/dist
    filter:
      - '**/*'
extraResources:
  - from: ../backend
    to: backend
    filter:
      - server
      - server.exe
      - offline.db
      - .env
linux:
  target:
    - AppImage
  category: Utility
win:
  target:
    - nsis
  artifactName: ${productName}-${version}-Setup.${ext}
nsis:
  oneClick: false
  perMachine: false
  allowElevation: true
  include: build/installer.nsh
electronVersion: 30.0.9
